//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto_Propietaria_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id_user { get; set; }
        public string NombreUser { get; set; }
        public string CorreoUser { get; set; }
        public Nullable<System.DateTime> EdadUser { get; set; }
    }
}
